changelog:
  exclude:
    authors:
      - octocat
  categories:
    - title: New Features
      labels:
        - new feature
    - title: Bug Fixes
      labels:
        - bug fix
    - title: Documentation Changes
      labels:
        - documentation
    - title: Other Changes
      labels:
        - miscellaneous
